# Generated by Django 3.1.1 on 2020-11-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
